// Templates use public Excalidraw skeletons. Bindings are generated by the engine.
// Text remains editable, and the complete template can be ungrouped.
export const drawingTemplates = [
  { id: 'blank', name: '空白画板' },
  { id: 'page', name: '数据页与记录' },
  { id: 'tree', name: 'B+ 树索引' },
  { id: 'scan', name: '索引扫描' },
  { id: 'timeline', name: '事务时间线' },
] as const

function rawTemplate(id: string): Record<string, any>[] {
  const box = (id: string, x: number, y: number, width: number, height: number, text: string, colour = '#e7f5ff') => ({ type: 'rectangle', id, x, y, width, height, backgroundColor: colour, label: { text, fontSize: 20, fontFamily: 2 } })
  const arrow = (id: string, start: string, end: string, text?: string) => ({ type: 'arrow', id, x: 0, y: 0, start: { id: start }, end: { id: end }, ...(text ? { label: { text, fontFamily: 2, fontSize: 16 } } : {}) })
  const title = (text: string) => ({ type: 'text', x: 0, y: -60, text, fontFamily: 2, fontSize: 24 })
  switch (id) {
    case 'page': return [title('数据页 · 主键顺序'), ...['页头', '记录 10', '记录 20', '记录 30', '空闲空间', '页目录'].map((text, i) => box(`row-${i}`, 0, i * 54, 240, 54, text, i === 4 ? '#ffffff' : '#e7f5ff')), box('next-page', 380, 100, 200, 180, '下一数据页'), arrow('page-link', 'row-3', 'next-page')]
    case 'tree': return [title('B+ 树索引'), box('root', 230, 0, 220, 60, '20  |  40'), box('leaf-a', 0, 180, 200, 70, '5  |  10  |  15', '#d3f9d8'), box('leaf-b', 240, 180, 200, 70, '20  |  25  |  30', '#d3f9d8'), box('leaf-c', 480, 180, 200, 70, '40  |  45  |  50', '#d3f9d8'), arrow('branch-a', 'root', 'leaf-a'), arrow('branch-b', 'root', 'leaf-b'), arrow('branch-c', 'root', 'leaf-c'), arrow('leaf-next-a', 'leaf-a', 'leaf-b'), arrow('leaf-next-b', 'leaf-b', 'leaf-c')]
    case 'scan': return [title('二级索引查询与回表'), box('query', 0, 0, 180, 90, '查询条件\nname = 张三'), box('index', 300, 0, 180, 90, '二级索引\n主键 = 20'), box('record', 600, 0, 180, 90, '聚簇索引\n完整记录'), arrow('lookup', 'query', 'index', '定位'), arrow('fetch', 'index', 'record', '回表')]
    case 'timeline': return [title('事务执行时间线'), box('t1-start', 0, 0, 170, 70, '事务 A\n开始'), box('t1-read', 250, 0, 170, 70, '读取数据'), box('t1-commit', 500, 0, 170, 70, '提交'), box('t2-start', 120, 180, 170, 70, '事务 B\n开始', '#fff3bf'), box('t2-write', 370, 180, 170, 70, '修改数据', '#fff3bf'), box('t2-commit', 620, 180, 170, 70, '提交', '#fff3bf'), arrow('a1', 't1-start', 't1-read'), arrow('a2', 't1-read', 't1-commit'), arrow('b1', 't2-start', 't2-write'), arrow('b2', 't2-write', 't2-commit')]
    default: return []
  }
}

export function templateSkeleton(id: string): Record<string, any>[] {
  const items = rawTemplate(id), nodes = new Map(items.map(e => [e.id, e]))
  return items.map(e => {
    if (e.type !== 'arrow') return e
    const a = nodes.get(e.start.id)!, b = nodes.get(e.end.id)!
    let x = a.x + a.width / 2, y = a.y + a.height / 2
    let endX = b.x + b.width / 2, endY = b.y + b.height / 2
    if (id === 'tree' && e.start.id === 'root') {
      y += a.height / 2 + 8; endY -= b.height / 2 + 8
    } else if (Math.abs(endX - x) > Math.abs(endY - y)) {
      const direction = Math.sign(endX - x)
      x += direction * (a.width / 2 + 8); endX -= direction * (b.width / 2 + 8)
    } else {
      const direction = Math.sign(endY - y)
      y += direction * (a.height / 2 + 8); endY -= direction * (b.height / 2 + 8)
    }
    return { ...e, x, y, width: Math.abs(endX - x), height: Math.abs(endY - y), points: [[0, 0], [endX - x, endY - y]] }
  })
}
